export interface Word {
	term: string;
	definition: string;
}

export interface Unit {
	id: string;
	name: string;
	quiz: Word[];
	test: Word[];
}

export const VOCABULARY: Unit[] = [
	{
		id: "unit1",
		name: "Unit 1",
		quiz: [
			{ term: "equate", definition: "使等同" },
			{ term: "dispatch", definition: "派遣；发送" },
			{ term: "evoke", definition: "引起；唤起" },
			{ term: "hypothesis", definition: "假设；假说" },
			{ term: "hurdle", definition: "障碍；困难" },
			{ term: "predominant", definition: "占优势的；占主导地位的；显著的" },
			{ term: "devastating", definition: "毁灭性的；破坏性极大的" },
			{ term: "intuitive", definition: "直觉的；凭直觉的" },
			{ term: "prone", definition: "易于遭受的；有倾向的" },
			{ term: "integrate", definition: "使结合；使融入；整合" },
		],
		test: [
			{ term: "modernize", definition: "使现代化" },
			{ term: "constitute", definition: "构成；组成" },
			{ term: "alert", definition: "使警觉；向……发出警报" },
			{ term: "urbanization", definition: "城市化" },
			{ term: "inclusive", definition: "包容广泛的；兼收并蓄的" },
			{ term: "instantaneous", definition: "即时的；瞬间的" },
			{ term: "to that end", definition: "为此；为了那个目的" },
			{ term: "commutes", definition: "通勤；往返上下班" },
			{ term: "underestimate", definition: "低估" },
			{ term: "proximity", definition: "接近；邻近" },
			{ term: "vulnerable", definition: "易受伤害的；脆弱的" },
			{ term: "on the horizon", definition: "即将发生；初露端倪" },
			{ term: "alternative", definition: "可替代的；供选择的" },
			{ term: "recreation", definition: "娱乐；消遣；休闲活动" },
			{ term: "inhabitants", definition: "居民；栖息者" },
		],
	},
	{
		id: "unit2",
		name: "Unit 2",
		quiz: [
			{ term: "costume", definition: "（代表某一特定地方或历史时期的）服装，装束" },
			{ term: "scar", definition: "使遭受（精神）创伤" },
			{ term: "resolution", definition: "（做某事的）决心" },
			{ term: "preface", definition: "给……做开场白；为……写序言" },
			{ term: "authentic", definition: "可靠的；真实的" },
			{ term: "eternity", definition: "永恒" },
			{ term: "fashionable", definition: "时尚的；流行的" },
			{ term: "record", definition: "记录；记下" },
			{ term: "is obsessed with", definition: "痴迷于；对……着迷" },
			{ term: "is responsible for", definition: "对……负责" },
		],
		test: [
			{ term: "knit", definition: "使紧密结合" },
			{ term: "manipulation", definition: "操纵；巧妙处理" },
			{ term: "outgoing", definition: "外向的" },
			{ term: "exempt", definition: "被豁免的；免除的" },
			{ term: "about", definition: "关于；就……而言" },
			{ term: "worn", definition: "磨损；使磨去" },
			{ term: "dietary", definition: "饮食的" },
			{ term: "generalize", definition: "概括；一概而论" },
			{ term: "ponder", definition: "思考；沉思" },
			{ term: "scarcity", definition: "稀缺；不足" },
			{ term: "preoccupied", definition: "全神贯注的；心事重重的" },
			{ term: "gratitude", definition: "感激；感谢" },
			{ term: "identify", definition: "识别；确认" },
			{ term: "soak", definition: "吸收；沉浸于" },
			{ term: "bare", definition: "光秃秃的；空的" },
		],
	},
	{
		id: "unit3",
		name: "Unit 3",
		quiz: [
			{ term: "aspire", definition: "追求；渴望" },
			{ term: "prototype", definition: "原型，雏形" },
			{ term: "attentive", definition: "专注的；专心的" },
			{ term: "commercialize", definition: "使商业化" },
			{ term: "consultation", definition: "专家咨询" },
			{ term: "ingenious", definition: "精巧的，巧妙的" },
			{ term: "strengthen", definition: "加强；增强" },
			{ term: "backing", definition: "支持；资助" },
			{ term: "helpful", definition: "有帮助的；有益的" },
			{ term: "regarding", definition: "关于；就……而言" },
		],
		test: [
			{ term: "showcase", definition: "展示；展现" },
			{ term: "emergence", definition: "出现；兴起" },
			{ term: "consultation", definition: "咨询；专家咨询" },
			{ term: "clash", definition: "冲突；争执" },
			{ term: "analogous", definition: "类似的；可比拟的" },
			{ term: "reflect", definition: "反思；认真思考" },
			{ term: "rating", definition: "评级；评分" },
			{ term: "climax", definition: "高潮；顶点" },
			{ term: "complicated", definition: "复杂的" },
			{ term: "straightforward", definition: "简单明了的；直接的" },
			{ term: "navigate", definition: "导航；找到途径" },
			{ term: "conducive", definition: "有助于……的" },
			{ term: "certified", definition: "认证；证明合格" },
			{ term: "single", definition: "single out：挑出；选出" },
			{ term: "compile", definition: "编纂；汇编" },
		],
	},
	{
		id: "unit4",
		name: "Unit 4",
		quiz: [
			{ term: "monumental", definition: "极大（坏，好等）的" },
			{ term: "integrity", definition: "完整；完全" },
			{ term: "timber", definition: "木材；木料" },
			{ term: "consume", definition: "消耗；消费；花费" },
			{ term: "affluence", definition: "富裕；富足" },
			{ term: "emission", definition: "排放物；散发物" },
			{ term: "breadth", definition: "广度；范围" },
			{ term: "timely", definition: "及时的" },
			{ term: "ecological", definition: "生态的" },
			{ term: "delay", definition: "延误；耽搁" },
		],
		test: [
			{ term: "fertile", definition: "肥沃的" },
			{ term: "threat", definition: "威胁" },
			{ term: "organism", definition: "生物；有机体" },
			{ term: "disposal", definition: "处理；处置" },
			{ term: "formulate", definition: "制定；构想" },
			{ term: "comply", definition: "遵守；服从" },
			{ term: "ozone", definition: "臭氧" },
			{ term: "habitat", definition: "栖息地" },
			{ term: "cut down on", definition: "减少；削减" },
			{ term: "plunge", definition: "跳入；猛冲" },
			{ term: "intolerant", definition: "不能容忍的" },
			{ term: "preside", definition: "主持；主管" },
			{ term: "contaminate", definition: "污染；弄脏" },
			{ term: "subscribe", definition: "同意；认同；订阅" },
			{ term: "peeled", definition: "剥去；撕下" },
		],
	},
	{
		id: "unit5",
		name: "Unit 5",
		quiz: [
			{ term: "sue", definition: "（通常为索赔而）起诉，控告" },
			{ term: "infinity", definition: "无限，无穷" },
			{ term: "blunt", definition: "钝的；不锋利的" },
			{ term: "diagnose", definition: "诊断；判断" },
			{ term: "condolence", definition: "同情，吊唁" },
			{ term: "oppressed", definition: "受压迫的；受压制的" },
			{ term: "exert", definition: "运用；施加" },
			{ term: "revenge", definition: "复仇；报复" },
			{ term: "humane", definition: "人道的；仁慈的" },
			{ term: "siege", definition: "围攻；包围" },
		],
		test: [
			{ term: "intrigued", definition: "激起兴趣；使好奇" },
			{ term: "exert", definition: "施加；运用" },
			{ term: "incurring", definition: "招致；引起" },
			{ term: "malpractice", definition: "渎职；医疗事故" },
			{ term: "revenge", definition: "报复；复仇" },
			{ term: "In adherence to", definition: "遵照；依照" },
			{ term: "sympathy", definition: "同情" },
			{ term: "oppressed", definition: "被压迫的；受压迫的" },
			{ term: "secular", definition: "世俗的；非宗教的" },
			{ term: "appeal", definition: "吸引；诉诸" },
			{ term: "denounce", definition: "谴责；公开指责" },
			{ term: "heritage", definition: "遗产；传统" },
			{ term: "coverage", definition: "报道；覆盖范围" },
			{ term: "tentative", definition: "暂定的；试探性的" },
			{ term: "realistic", definition: "现实的；实际可行的" },
		],
	},
	{
		id: "unit6",
		name: "Unit 6",
		quiz: [
			{ term: "principle", definition: "原则；原理；基本的观念" },
			{ term: "prohibitive", definition: "（价格）高得负担不起的，贵得使人望而却步的" },
			{ term: "axis", definition: "轴；轴线" },
			{ term: "gadget", definition: "设计精巧的小机械（或工具）" },
			{ term: "lump", definition: "（不定形的）块" },
			{ term: "blade", definition: "桨叶；螺旋桨叶；叶片状物" },
			{ term: "developed from", definition: "源自；由……发展而来" },
			{ term: "intensely", definition: "强烈地；紧张地" },
			{ term: "change … into …", definition: "把……变成……" },
			{ term: "depends on", definition: "依靠；取决于" },
		],
		test: [
			{ term: "layer", definition: "层" },
			{ term: "eventual", definition: "最终的" },
			{ term: "poll", definition: "民意调查；投票" },
			{ term: "fill up", definition: "装满；加满" },
			{ term: "factor in", definition: "把……考虑进去" },
			{ term: "linear", definition: "线性的" },
			{ term: "promising", definition: "有前途的；有希望的" },
			{ term: "soluble", definition: "可解决的；可溶解的" },
			{ term: "rescue", definition: "营救；救援" },
			{ term: "coherent", definition: "连贯的；条理清楚的" },
			{ term: "affluent", definition: "富裕的" },
			{ term: "level", definition: "level off：趋于平稳" },
			{ term: "estimate", definition: "估计；估算" },
			{ term: "starved", definition: "缺乏的；极需要的" },
			{ term: "account for", definition: "占；解释" },
		],
	},
];

export const WORD_LOOKUP = new Map<string, Word>();

VOCABULARY.forEach((unit) => {
	const allWords = [...unit.quiz, ...unit.test];
	allWords.forEach((w) => {
		WORD_LOOKUP.set(w.term.toLowerCase(), w);
		WORD_LOOKUP.set(w.definition, w);
	});
});
